# Generated by Django 4.1 on 2022-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=16, verbose_name='Бренд')),
                ('model', models.CharField(max_length=32, verbose_name='Модель')),
                ('condition', models.CharField(max_length=20, verbose_name='Состояние')),
                ('quantity', models.IntegerField(verbose_name='Колличество')),
                ('color', models.TextField(verbose_name='Цвет')),
                ('info', models.TextField(verbose_name='Характеристики')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
